export const traerTiquetesComprados = [
    {
      id: 1,
      codeSeat: "A7",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 2,
      codeSeat: "A8",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 3,
      codeSeat: "A9",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 4,
      codeSeat: "B7",
      idCinema: "Oviedo",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 5,
      codeSeat: "B8",
      idCinema: "Oviedo",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "13:00",
    },
    {
      id: 5,
      codeSeat: "B8",
      idCinema: "Oviedo",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "13:00",
    },
    {
      id: 6,
      codeSeat: "B10",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 7,
      codeSeat: "B11",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 8,
      codeSeat: "B12",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 9,
      codeSeat: "C5",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 10,
      codeSeat: "C6",
      idCinema: "Arkadia",
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
  ];